### ISSUE TITLE
Remove download-init-package input variable

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns/setup-zarf#39]
Using a zarf init package with zarf is likely to be a very common use-case, so reducing the cognitive load on users for what inputs they need to provide would likely improve user experience.

The action currently checks if this input variable is set to true, and downloads an init package if so. Otherwise, it does not download one.

We want the default behavior to be to download an init package, and for the user to not have to think about whether they want one or not

**Comment by jeff-mccoy** [comment]
Default should be false, it's a large binary that will slow down workflow when an init package is only needed for initializing a cluster. I think instead we can add a "confirm init download" thing to zarf itself and have viper set it via this action by default so that you don't even need the "download init package" variable in the future.  Also note, github caching is actually slower than just doing single-large blob loads directly.

**Comment by lucasrod16** [comment]
We have decided to keep the `download-init-package` variable, and make it an optional input that is set to false.

See this [PR](https://github.com/defenseunicorns/setup-zarf/pull/42) for more information
